#!/bin/bash
#
# Replace Nordic SDK source and header files
# This script must be run from the nrf/ directory;
# not from the nrf/nordic/sdk-modified directory.

nrf_sdk=external/nrf_sdk

function copy_sdk_file() {
    sdk_modified_file=${1}
    sdk_target_file=${2}

    filename=$(basename -- "${sdk_target_file}")
    extension="${filename##*.}"
    filename="${filename%.*}"
    dirname=$(dirname -- "${sdk_target_file}")

    sdk_orig_file=${dirname}/${filename}.orig.${extension}
    if [ -e ${sdk_orig_file} ] ; then
        echo "error: ${sdk_orig_file} already exists, copy refused"
    else
        mv -v ${sdk_target_file} ${dirname}/${filename}.orig.${extension}
        cp -v ${sdk_modified_file} ${sdk_target_file}
    fi
}

sdk_modified_file=nordic/sdk-modified/cmsis_gcc.h
sdk_target_file=${nrf_sdk}/components/toolchain/cmsis/include/cmsis_gcc.h
copy_sdk_file ${sdk_modified_file} ${sdk_target_file}
