#!/bin/sh
#
# Replace Nordic SDK source and header files
# This script should run from the nrf/notdic/sdk-modified directory

function move_sdk_file() {
    sdk_file=$1
	filename=$(basename -- "$sdk_file")
	extension="${filename##*.}"
	filename="${filename%.*}"
	dirname=$(dirname -- "$sdk_file")

	sdk_orig_file=$dirname/$filename.orig.$extension
	if [ -e $sdk_orig_file ] ; then
		echo "$sdk_orig_file already exists, $sdk_file unchanged"
	else
		mv $sdk_file $dirname/$filename.orig.$extension
	fi
}

function replace_sdk_file() {
    sdk_file=$1
	filename=$(basename -- "$sdk_file")

	if [ ! -e $sdk_file ] ; then
		cp -v ./$filename $sdk_file
	else
		echo "$sdk_file already exists, not replaced"
	fi
}

SDK_ROOT=../../sdk

if [ ! -e $SDK_ROOT ] ; then
	echo "The nrf/sdk link does not exist"
	exit 1
fi

sdk_file=$SDK_ROOT/components/libraries/util/nrf_assert.h
move_sdk_file $sdk_file

sdk_file=$SDK_ROOT/components/libraries/util/app_util.h
move_sdk_file    $sdk_file
replace_sdk_file $sdk_file

# sdk_file=$SDK_ROOT/components/libraries/util/app_error_weak.c
# move_sdk_file    $sdk_file
# replace_sdk_file $sdk_file

sdk_file=$SDK_ROOT/components/toolchain/cmsis/include/cmsis_gcc.h
move_sdk_file    $sdk_file
replace_sdk_file $sdk_file

